#!/bin/bash
#
# MalRecon - A Basic Malware Reconnaissance Tool, by Outrider
#
# Usage:	Installs MalRecon dependencies and configures symbolic links
# Syntax:	./install
# Example:	./install
#
# Get the latest version here: https://github.com/0utrider/malrecon
#
#
#    Copyright 2017 Outrider - keybase.io/outrider
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Banner
echo ""
echo -e "\033[38;5;0m                                             \033[0m"
echo -e "\033[38;5;196m    (_     __)       \033[38;5;63m  _____                 \033[0m"
echo -e "\033[38;5;196m      /|  /|       /)\033[38;5;63m    /   )               \033[0m"
echo -e "\033[38;5;196m     / | / |  _   // \033[38;5;63m   /__ /  _  _  _____   \033[0m"
echo -e "\033[38;5;196m  ) /  |/  |_(_(_(/_ \033[38;5;63m  /   \__(/_(__(_) / (_ \033[0m"
echo -e "\033[38;5;196m (_/   '             \033[38;5;63m /                      \033[0m"
echo -e "\033[38;5;254m                               by Outrider   \033[0m"
echo -e "\033[38;5;0m                                             \033[0m"
echo -e "      Basic Malware Reconnaissance Tool      "
echo ""
echo "           https://git.io/0utrider           "
echo ""

# Define prerequisite packages
installPax="binutils p7zip-full"

# Set directory
## Below it is trying to ensure that the commands are run out of the real malrecon directory, resolving symlinks
installPath=$(dirname $(realpath -s $0))
cd $installPath
echo -e "Setting \033[38;5;254mpath\033[0m to \033[38;5;254m$installPath\033[0m ..."

# Permissions: allow execute on scripts
echo -e "Setting \033[38;5;254mpermissions\033[0m ..."
chmod +x install malrecon update

# Create symbolic link
echo -e "Creating \033[38;5;254msymbolic link\033[0m ..."
ln -s $installPath/malrecon /usr/bin/malrecon

# Install dependencies
## Package manager check
installApt=$(which apt-get)
installPac=$(which pacman)
installYum=$(which yum)

if [[ ! -z $installApt ]]; then		# if apt-get exists on the system, install dependencies
  apt-get update > /dev/null 2>&1
  apt-get install -y $installPax > /dev/null 2>&1
elif [[ ! -z $installPac ]]; then	# if pacman exists on the system, install dependencies
  pacman -Sy > /dev/null 2>&1
  pacman -S $installPax > /dev/null 2>&1
  pacman -S p7zip > /dev/null 2>&1
## TO-DO: (RPM fork)
###elif [[ ! -z $installYum ]]; then	# if yum exists on the system, install dependencies
###  yum 
else
    echo -e "\033[38;5;196mCannot find APT-GET, PACMAN, or YUM\033[0m"
	echo ""
	echo "You will need to install the following:"
	echo $installPax
	echo ""
    exit 1;
fi

# (Not finished with this script yet!)
echo ""
echo "(Still working on this.)"
echo ""
