#!/bin/bash
#
# MalRecon - A Basic Malware Reconnaissance Tool, by Outrider
#
# Usage:	Updates MalRecon by utilizing Git
# Syntax:	./update
# Example:	./update
#
# Get the latest version here: https://github.com/0utrider/malrecon
#
#
#    Copyright 2017 Outrider - keybase.io/outrider
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Banner
echo ""
echo -e "\033[38;5;0m                                             \033[0m"
echo -e "\033[38;5;196m    (_     __)       \033[38;5;63m  _____                 \033[0m"
echo -e "\033[38;5;196m      /|  /|       /)\033[38;5;63m    /   )               \033[0m"
echo -e "\033[38;5;196m     / | / |  _   // \033[38;5;63m   /__ /  _  _  _____   \033[0m"
echo -e "\033[38;5;196m  ) /  |/  |_(_(_(/_ \033[38;5;63m  /   \__(/_(__(_) / (_ \033[0m"
echo -e "\033[38;5;196m (_/   '             \033[38;5;63m /                      \033[0m"
echo -e "\033[38;5;254m                               by Outrider   \033[0m"
echo -e "\033[38;5;0m                                             \033[0m"
echo -e "      Basic Malware Reconnaissance Tool      "
echo ""
echo "           https://git.io/0utrider           "
echo ""

# Set directory
## Below it is trying to ensure that the commands are run out of the real malrecon directory, resolving symlinks
updatePath=$(dirname $(realpath -s $0))
cd $updatePath

# Update using Git
echo "Running updates ..."
git fetch -q origin master
git reset -q --hard origin/master
git clean -dfq

# Reset permissions
chmod +x install malrecon update

# That's a wrap!
echo -e "\033[30;48;5;82mDone.\033[0m"
echo ""
